#pragma once

// Ids for serialising attributes of compilers
// and deserialising them into a VM
#define INT_ID 0xAAAAAAAAAAAAAAAA
#define DOUBLE_ID 0xBBBBBBBBBBBBBBBB
#define BOOL_ID 0xCCCCCCCCCCCCCCCC
#define CHAR_ID 0xDDDDDDDDDDDDDDDD
#define STRING_ID 0xEEEEEEEEEEEEEEEE
#define CODE_ID 0xFFFFFFFFFFFFFFFF
#define STRUCT_TREE_ID 0xABABABABABABABAB
#define LIB_FUNC_ID 0xBCBCBCBCBCBCBCBC
